version: '2'
services:

  postgres:
    hostname: postgres
    image: 'postgres:10.3'
    ports:
      - '15432:15432'
    environment:
      POSTGRES_PASSWORD: swarm
      POSTGRES_USER: swarm
      POSTGRES_DB: test
      PGPORT: 15432

  mysql:
    hostname: mysql
    image: 'mysql:5.7'
    ports:
      - '13306:13306'
    command:
      mysqld --port 13306
    environment:
      MYSQL_USER: swarm
      MYSQL_PASSWORD: swarm
      MYSQL_ROOT_PASSWORD: swarm
      MYSQL_DATABASE: test
